### PR TITLE
Add Exceptions, rename parameter, fix Code Climate

### PR DESCRIPTION
**Pull request by djlambert**
- Add type checks in ValidatorStack.
- Add UnknownType exception.
- There is a key "value" in the value array. Change/rename references to value array to Object Data Array. Now the Object Data Array contains a key named "value"
- Fix Code Climate
- Added documentation to contributing

### CODE REVIEW

**Comment by djlambert** [comment]
- Rename Converter to Formatter
- WKB formatter WIP

**Comment by djlambert** [comment]
- WKB formatter finished for primary types
- Added method `DataFactory::convert()` to allow conversion between known types! WKT->WKB, WKB->WKT, etc.

**Comment by djlambert** [comment]
Can we merge this and then merge into master? I'd like to get some coverage reports.

**Comment by ddproxy** [comment]
LGTM

**Pull request merged**
